query findListsByUser {
  findListsByUser {
    id
    name
    position
    tasks {
      id
      columnPos
      name
      notes
      projects {
        id
        name
        color {
          id
          name
          hex
        }
      }
    }
  }
}

