mutation updateTask (
  $id: String!,
  $name: String!,
  $notes: String!,
  $projectIds: [ID!],
  $columnPos: Float,
  $listId: String
) {
  updateTask(updateInput: {
    id: $id,
    name: $name,
    notes: $notes,
    projectIds: $projectIds,
    columnPos: $columnPos,
    listId: $listId
  }) {
    id,
    name,
    notes,
    projects {
      id,
      name
    },
    columnPos
  }
}
