mutation updateTask (
  $id: String!,
  $name: String!,
  $notes: String!,
  $projectIds: [ID!]
) {
  updateTask(updateInput: {
    id: $id,
    name: $name,
    notes: $notes,
    projectIds: $projectIds
  }) {
    id,
    name,
    notes,
    projects {
      id,
      name
    }
  }
}
